name: Deploy AWS Lambdas (matrix)

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  LAMBDA_DIR: lambda
  S3_BUCKET: ${{ secrets.S3_BUCKET }}

jobs:
  deploy:
    strategy:
      matrix:
        lambda: [locations, processor, requests, supplies]
    name: Deploy Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set lambda name
        run: |
          if [ "${{ matrix.lambda }}" == locations ]; then
              echo "LAMBDA_NAME=GetLocations" >> $GITHUB_ENV
          elif [ "${{ matrix.lambda }}" == processor ]; then
              echo "LAMBDA_NAME=SaveRequest" >> $GITHUB_ENV
          elif [ "${{ matrix.lambda }}" == requests ]; then
              echo "LAMBDA_NAME=PostRequest" >> $GITHUB_ENV
          elif [ "${{ matrix.lambda }}" == supplies ]; then
              echo "LAMBDA_NAME=GetSupplies" >> $GITHUB_ENV
          else
            exit 1
          fi
      - run: |
          echo "lambda-dir: ${LAMBDA_DIR}/${{ matrix.lambda }}"
          echo "lambda-name: ${LAMBDA_NAME}"
          echo "s3-bucket: ${S3_BUCKET}"
          echo "s3-key: ${{ matrix.lambda }}.zip"

#      - uses: ukraine-taskforce/requests-backend@main
#        with:
#          lambda-dir: ${LAMBDA_DIR}/${{ matrix.lambda }}
#          lambda-name: ${LAMBDA_NAME}
#          s3-bucket: ${S3_BUCKET}
#          s3-key: ${{ matrix.lambda }}.zip
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
