name: Deploy AWS Lambdas (dev, manual)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: branch to deploy from to dev
        required: true
        default: main

env:
  LAMBDA_DIR: lambda
  S3_BUCKET: ${{ secrets.S3_BUCKET }}

jobs:
  locations:
    name: Deploy Locations Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.event.inputs.branch }}
      - uses: ukraine-taskforce/requests-backend@main
        with:
          lambda-dir: ${LAMBDA_DIR}/locations
          lambda-name: GetLocations
          s3-bucket: ${S3_BUCKET}
          s3-key: locations.zip
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  processor:
    name: Deploy Processor Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.event.inputs.branch }}
      - uses: ukraine-taskforce/requests-backend@main
        with:
          lambda-dir: lambda/processor
          lambda-name: SaveRequest
          s3-bucket: ${S3_BUCKET}
          s3-key: processor.zip
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  requests:
    name: Deploy Requests Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.event.inputs.branch }}
      - uses: ukraine-taskforce/requests-backend@main
        with:
          lambda-dir: lambda/requests
          lambda-name: PostRequest
          s3-bucket: ${S3_BUCKET}
          s3-key: requests.zip
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  supplies:
    name: Deploy Supplies Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.event.inputs.branch }}
      - uses: ukraine-taskforce/requests-backend@main
        with:
          lambda-dir: lambda/supplies
          lambda-name: GetSupplies
          s3-bucket: ${S3_BUCKET}
          s3-key: supplies.zip
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
