name: Deploy AWS Lambdas (prod)

permissions:
  id-token: write   # Allow assume IAM Role via GitHub OIDC
  contents: read    # This is required for actions/checkout@v2

on:
  push:
    tags:
      - v*

env:
  LAMBDA_DIR: lambda
  S3_BUCKET: ${{ secrets.PROD_S3_BUCKET }}

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        lambda: [locations, processor, requests, supplies, requests-aggregated, requests-list]
    name: Deploy Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set lambda name
        run: |
          if [ "${{ matrix.lambda }}" == locations ]; then LAMBDA_NAME=GetLocations
          elif [ "${{ matrix.lambda }}" == processor ]; then LAMBDA_NAME=SaveRequest
          elif [ "${{ matrix.lambda }}" == requests ]; then LAMBDA_NAME=PostRequest
          elif [ "${{ matrix.lambda }}" == supplies ]; then LAMBDA_NAME=GetSupplies
          elif [ "${{ matrix.lambda }}" == requests-aggregated ]; then LAMBDA_NAME=GetRequestsAggregated
          elif [ "${{ matrix.lambda }}" == requests-list ]; then LAMBDA_NAME=ListRequests
          else exit 1
          fi
          echo "LAMBDA_NAME=${LAMBDA_NAME}" >> $GITHUB_ENV
      - uses: ukraine-taskforce/update-lambda-action@v0.0.1
        with:
          lambda-dir: ${{ env.LAMBDA_DIR }}/${{ matrix.lambda }}
          lambda-name: ${{ env.LAMBDA_NAME }}
          s3-bucket: ${{ env.S3_BUCKET }}
          s3-key: ${{ matrix.lambda }}.zip
          role-arn: ${{ secrets.PROD_DEPLOY_ROLE_ARN }}
